name: necklace
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  web_socket_channel: ^2.4.0
  http: ^1.3.0
  http_parser: ^4.1.2
  path_provider: ^2.1.5  # For temporary file handling
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  animated_background: ^2.0.0
  glassmorphism: ^3.0.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
